import { allRules, docsUrlFor, type Category } from '@svelte-vitals/core';

// Category order + labels for the generated rule digest. Kept in the same order the
// project's docs use elsewhere (SEO, Performance, Correctness, Security, Architecture).
const CATEGORY_ORDER: Category[] = ['seo', 'performance', 'correctness', 'security', 'architecture'];

const CATEGORY_LABELS: Record<Category, string> = {
  seo: 'SEO',
  performance: 'Performance',
  correctness: 'Correctness',
  security: 'Security',
  architecture: 'Architecture'
};

/** Collapse embedded newlines so a rule stays on a single Markdown list line. */
export function oneLine(text: string): string {
  return text.replace(/\r?\n+/g, ' ').trim();
}

function ruleLine(rule: (typeof allRules)[number]): string {
  const fixPart = rule.fix?.description ? ` Fix: ${oneLine(rule.fix.description)}` : '';
  return `- **${rule.id} — ${oneLine(rule.title)}** (${rule.severity}): ${oneLine(rule.rationale)}${fixPart} ([docs](${docsUrlFor(rule.id)}))`;
}

function ruleDigest(): string {
  return CATEGORY_ORDER.map((category) => {
    const lines = allRules
      .filter((r) => r.category === category)
      .map(ruleLine)
      .join('\n');
    return `### ${CATEGORY_LABELS[category]}\n\n${lines}`;
  }).join('\n\n');
}

function sharedBody(version: string): string {
  return `<!-- Generated by \`svelte-vitals install\` (svelte-vitals ${version}). Re-run with --force to refresh. -->

# svelte-vitals

## When to use

Use this whenever you are writing or reviewing SvelteKit route files (\`+page.svelte\`, \`+layout.svelte\`) or components in this project — svelte-vitals statically checks SEO, performance, correctness, security, and architecture patterns.

## Playbook

1. After writing or editing code, run \`npx svelte-vitals . --diff --reporter agent\` and fix any findings it reports.
2. Before committing, run \`npx svelte-vitals . --staged\` as a pre-commit gate.
3. For a rule's full rationale and fix examples, use the \`explain_rule\` MCP tool (svelte-vitals MCP server) or open its docs link below.

## Rule digest

${ruleDigest()}
`;
}

/** Generate the Claude Code skill file content (SKILL.md). */
export function buildSkillMarkdown(version: string): string {
  const frontmatter = `---
name: svelte-vitals
description: Use when writing or reviewing SvelteKit routes/components — svelte-vitals rule knowledge (SEO, performance, correctness, security, architecture) and how to run the scanner.
---`;
  return `${frontmatter}\n\n${sharedBody(version)}`;
}

/** Generate the Cursor project rules file content (.mdc). */
export function buildCursorRules(version: string): string {
  const frontmatter = `---
description: svelte-vitals code-health rules for SvelteKit (SEO, performance, correctness, security, architecture)
globs: ["**/*.svelte", "src/routes/**"]
alwaysApply: false
---`;
  return `${frontmatter}\n\n${sharedBody(version)}`;
}
