import { type Category } from '@svelte-vitals/core';
import { allRules, docsUrlFor, type RuleOptionSpec } from '@svelte-vitals/core/internal';

// Category order + labels for the generated rule digest. Kept in the same order the
// project's docs use elsewhere (SEO, Performance, Correctness, Security, Architecture, Accessibility).
const CATEGORY_ORDER: Category[] = ['seo', 'performance', 'correctness', 'security', 'architecture', 'a11y'];

const CATEGORY_LABELS = {
  seo: 'SEO',
  performance: 'Performance',
  correctness: 'Correctness',
  security: 'Security',
  architecture: 'Architecture',
  a11y: 'Accessibility'
} satisfies Record<Category, string>;

/** Collapse embedded newlines so a rule stays on a single Markdown list line. */
export function oneLine(text: string): string {
  return text.replace(/\r?\n+/g, ' ').trim();
}

/** Whether an option's default carries no signal to check against: an empty list or map. An
 * integer option always has a real numeric default (0 is a meaningful threshold, not "unset"),
 * so it never counts as empty here. */
export function isEmptyDefault(spec: RuleOptionSpec): boolean {
  if (spec.kind === 'string-list') return spec.default.length === 0;
  if (spec.kind === 'string-map') return Object.keys(spec.default).length === 0;
  return false;
}

/**
 * Whether a rule does nothing until a project configures it: it declares options, and every
 * one of them defaults to empty. Derived from the rule's own `options` spec rather than
 * hard-coding a rule id, so a future L3-layer rule (declared, never inferred) is picked up the
 * same way `architecture/private-scope-import` is today.
 */
export function isInertUntilConfigured(rule: (typeof allRules)[number]): boolean {
  if (!rule.options) return false;
  const specs = Object.values(rule.options);
  return specs.length > 0 && specs.every(isEmptyDefault);
}

function ruleLine(rule: (typeof allRules)[number]): string {
  const fixPart = rule.fix?.description ? ` Fix: ${oneLine(rule.fix.description)}` : '';
  const inertPart = isInertUntilConfigured(rule) ? ' (inert until configured)' : '';
  return `- **${rule.id} — ${oneLine(rule.title)}** (${rule.severity}): ${oneLine(rule.rationale)}${fixPart}${inertPart} ([docs](${docsUrlFor(rule.id)}))`;
}

/** Prefixes the digest. A rule only carries `fix.description` when it ships one canonical fix for
 * every occurrence; the rest build their fix text per finding, so a missing `Fix:` here would
 * otherwise read as "this rule has no fix". */
const DIGEST_NOTE =
  "A `Fix:` below is the rule's canonical fix, the same for every occurrence. A line without one is not a rule without a fix — those rules word their fix per finding, so take it from the finding itself: `recommendation` on each issue in `--reporter json`, printed as `Fix:` by `--reporter agent`.";

export function ruleDigest(): string {
  const categories = CATEGORY_ORDER.map((category) => {
    const lines = allRules
      .filter((r) => r.category === category)
      .map(ruleLine)
      .join('\n');
    return `### ${CATEGORY_LABELS[category]}\n\n${lines}`;
  }).join('\n\n');
  return `${DIGEST_NOTE}\n\n${categories}`;
}

/** Generated-by comment for copies written into a project by `svelte-vitals install`. */
export function installHeader(version: string): string {
  return `<!-- Generated by \`svelte-vitals install\` (svelte-vitals ${version}). Re-run \`svelte-vitals install --refresh\` to regenerate. -->`;
}

/** Generated-by comment for the repo-root `skills/` copies (the skills.sh install source).
 * Version-free on purpose: an embedded version would go stale on every release PR and trip
 * the drift test in `test/skills-repo.test.ts`. */
export const REPO_SKILLS_HEADER =
  '<!-- Generated by `pnpm --filter svelte-vitals run gen:skills` — do not edit by hand. -->';

function sharedBody(header: string): string {
  return `${header}

# svelte-vitals

## When to use

Use this whenever you are writing or reviewing SvelteKit route files (\`+page.svelte\`, \`+layout.svelte\`) or components in this project — svelte-vitals statically checks SEO, performance, correctness, security, architecture, and accessibility patterns.

## Playbook

1. After writing or editing code, run \`npx svelte-vitals . --diff --reporter agent\` and fix any findings it reports.
2. Before committing, run \`npx svelte-vitals . --staged\` as a pre-commit gate.
3. For a rule's full rationale, configurable options and fix examples, run \`npx svelte-vitals explain <rule-id>\` (add \`--json\` for a structured object) or open its docs link below. The fix text for a specific finding comes from the run itself, not from \`explain\` — see the note above the rule digest.
4. When a finding is correct by design — a reviewed \`{@html}\` that is already sanitized, a deliberate \`$effect\` — clear it with an inline directive instead of changing the code: \`<!-- svelte-vitals-disable-next-line <rule-id> -->\` on the line above in markup, or \`// svelte-vitals-disable-next-line <rule-id>\` inside \`<script>\`. Review it first; never suppress a finding you have not read.
5. Exit codes: \`0\` nothing failing, \`1\` a critical finding (or your \`--fail-on\`/\`--min-health\` threshold), \`2\` the run itself failed — a \`2\` says nothing about the code, so never read it as a clean or dirty result.
6. For anything else — reporters, the config file, scoping to a change, CI, monorepos — run \`npx svelte-vitals docs list\` and then \`npx svelte-vitals docs show <name>\`. Those guides ship inside the CLI, so they match the version installed here; prefer them over searching the web.

## Rule digest

${ruleDigest()}
`;
}

/** Generate the Claude Code skill file content (SKILL.md). */
export function buildSkillMarkdown(header: string): string {
  const frontmatter = `---
name: svelte-vitals
description: Use when writing or reviewing SvelteKit routes/components — svelte-vitals rule knowledge (SEO, performance, correctness, security, architecture, accessibility) and how to run the scanner.
---`;
  return `${frontmatter}\n\n${sharedBody(header)}`;
}

/** Generate the Cursor project rules file content (.mdc). */
export function buildCursorRules(header: string): string {
  const frontmatter = `---
description: svelte-vitals code-health rules for SvelteKit (SEO, performance, correctness, security, architecture, accessibility)
globs: ["**/*.svelte", "src/routes/**"]
alwaysApply: false
---`;
  return `${frontmatter}\n\n${sharedBody(header)}`;
}
