import { allRules, docsUrlFor, type Category, type RuleOptionSpec } from '@svelte-vitals/core';

// Category order + labels for the generated rule digest. Kept in the same order the
// project's docs use elsewhere (SEO, Performance, Correctness, Security, Architecture).
const CATEGORY_ORDER: Category[] = ['seo', 'performance', 'correctness', 'security', 'architecture'];

const CATEGORY_LABELS: Record<Category, string> = {
  seo: 'SEO',
  performance: 'Performance',
  correctness: 'Correctness',
  security: 'Security',
  architecture: 'Architecture'
};

/** Collapse embedded newlines so a rule stays on a single Markdown list line. */
export function oneLine(text: string): string {
  return text.replace(/\r?\n+/g, ' ').trim();
}

/** Whether an option's default carries no signal to check against: an empty list or map. An
 * integer option always has a real numeric default (0 is a meaningful threshold, not "unset"),
 * so it never counts as empty here. */
function isEmptyDefault(spec: RuleOptionSpec): boolean {
  if (spec.kind === 'string-list') return spec.default.length === 0;
  if (spec.kind === 'string-map') return Object.keys(spec.default).length === 0;
  return false;
}

/**
 * Whether a rule does nothing until a project configures it: it declares options, and every
 * one of them defaults to empty. Derived from the rule's own `options` spec rather than
 * hard-coding a rule id, so a future L3-layer rule (declared, never inferred) is picked up the
 * same way `architecture/private-scope-import` is today.
 */
function isInertUntilConfigured(rule: (typeof allRules)[number]): boolean {
  if (!rule.options) return false;
  const specs = Object.values(rule.options);
  return specs.length > 0 && specs.every(isEmptyDefault);
}

function ruleLine(rule: (typeof allRules)[number]): string {
  const fixPart = rule.fix?.description ? ` Fix: ${oneLine(rule.fix.description)}` : '';
  const inertPart = isInertUntilConfigured(rule) ? ' (inert until configured)' : '';
  return `- **${rule.id} — ${oneLine(rule.title)}** (${rule.severity}): ${oneLine(rule.rationale)}${fixPart}${inertPart} ([docs](${docsUrlFor(rule.id)}))`;
}

export function ruleDigest(): string {
  return CATEGORY_ORDER.map((category) => {
    const lines = allRules
      .filter((r) => r.category === category)
      .map(ruleLine)
      .join('\n');
    return `### ${CATEGORY_LABELS[category]}\n\n${lines}`;
  }).join('\n\n');
}

function sharedBody(version: string): string {
  return `<!-- Generated by \`svelte-vitals install\` (svelte-vitals ${version}). Re-run with --force to refresh. -->

# svelte-vitals

## When to use

Use this whenever you are writing or reviewing SvelteKit route files (\`+page.svelte\`, \`+layout.svelte\`) or components in this project — svelte-vitals statically checks SEO, performance, correctness, security, and architecture patterns.

## Playbook

1. After writing or editing code, run \`npx svelte-vitals . --diff --reporter agent\` and fix any findings it reports.
2. Before committing, run \`npx svelte-vitals . --staged\` as a pre-commit gate.
3. For a rule's full rationale and fix examples, use the \`explain_rule\` MCP tool (svelte-vitals MCP server) or open its docs link below.

## Rule digest

${ruleDigest()}
`;
}

/** Generate the Claude Code skill file content (SKILL.md). */
export function buildSkillMarkdown(version: string): string {
  const frontmatter = `---
name: svelte-vitals
description: Use when writing or reviewing SvelteKit routes/components — svelte-vitals rule knowledge (SEO, performance, correctness, security, architecture) and how to run the scanner.
---`;
  return `${frontmatter}\n\n${sharedBody(version)}`;
}

/** Generate the Cursor project rules file content (.mdc). */
export function buildCursorRules(version: string): string {
  const frontmatter = `---
description: svelte-vitals code-health rules for SvelteKit (SEO, performance, correctness, security, architecture)
globs: ["**/*.svelte", "src/routes/**"]
alwaysApply: false
---`;
  return `${frontmatter}\n\n${sharedBody(version)}`;
}
