// Pure functions for generating src/html-spec/generated.ts from @markuplint/html-spec's JSON.
// Split from gen-html-spec.js (the thin I/O main) so test/html-spec.test.ts can re-run the same
// projection against the installed package and compare, offline — the schema-vocab pattern.
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);

/** The package's `exports` map has `./json` but no `./package.json`, so resolve through the data file. */
export function resolveHtmlSpec() {
  const jsonPath = require.resolve('@markuplint/html-spec/json');
  const pkg = JSON.parse(readFileSync(join(dirname(jsonPath), 'package.json'), 'utf8'));
  const license = readFileSync(join(dirname(jsonPath), 'LICENSE'), 'utf8').trim();
  return { jsonPath, version: pkg.version, license };
}

/** Attribute-row keys the rules read; everything else on a row is prose or presentation. */
const ATTR_KEYS = [
  'type',
  'required',
  'requiredEither',
  'deprecated',
  'obsolete',
  'nonStandard',
  'experimental',
  'ineffective',
  'condition',
  'noUse'
];

function projectAttrs(attrs) {
  const out = {};
  for (const [name, row] of Object.entries(attrs ?? {})) {
    const kept = {};
    for (const k of ATTR_KEYS) if (row[k] !== undefined) kept[k] = row[k];
    out[name] = kept;
  }
  return out;
}

/**
 * `permittedRoles` comes in four shapes; rules get one: a role-name list, or the sentinel `'any'`.
 * `true` (72 HTML elements) and the `{"core-aam", "graphics-aam"}` object (16 `svg:*` entries)
 * both mean "any role"; `false` means none; a list may mix names with `{name, deprecated}` objects.
 */
function permittedRoles(v) {
  if (v === true) return 'any';
  if (v === false || v === undefined) return [];
  if (Array.isArray(v)) return v.map((r) => (typeof r === 'string' ? r : r.name));
  return 'any';
}

/**
 * Project the dataset down to what the rules read. Prose (`description`, `cite`, `defaultValue`,
 * `animatable`) goes; so does everything from `#aria` except the deprecation and per-role property
 * rows, and from those rows the `required` field is dropped so this module can never answer what
 * a role requires — that stays `aria-query`'s question (design 2026-08-18-html-spec-data-source).
 */
export function projectHtmlSpec(raw) {
  const elements = {};
  for (const s of raw.specs) {
    const aria = s.aria ?? {};
    elements[s.name] = {
      categories: s.categories ?? [],
      ...(s.deprecated ? { deprecated: true } : {}),
      ...(s.obsolete ? { obsolete: true } : {}),
      contentModel: s.contentModel ?? {},
      aria: {
        ...(typeof aria.implicitRole === 'string' ? { implicitRole: aria.implicitRole } : {}),
        permittedRoles: permittedRoles(aria.permittedRoles)
      },
      globalAttrs: Object.keys(s.globalAttrs ?? {}),
      attributes: projectAttrs(s.attributes)
    };
  }
  const globalAttrs = {};
  for (const [group, attrs] of Object.entries(raw.def['#globalAttrs'])) globalAttrs[group] = projectAttrs(attrs);
  const a13 = raw.def['#aria']['1.3'];
  const roleRow = (r) => ({
    ...(r.deprecated ? { deprecated: true } : {}),
    ownedProperties: (r.ownedProperties ?? []).map((p) => ({
      name: p.name,
      ...(p.deprecated ? { deprecated: true } : {})
    })),
    prohibitedProperties: r.prohibitedProperties ?? []
  });
  const roles = {};
  for (const r of [...a13.roles, ...(a13.graphicsRoles ?? [])]) roles[r.name] = roleRow(r);
  return {
    elements,
    contentModels: raw.def['#contentModels'],
    globalAttrs,
    aria: {
      roles,
      deprecatedProps: a13.props.filter((p) => p.deprecated).map((p) => p.name)
    }
  };
}

/**
 * The data is emitted as one JSON.parse'd string, not an object literal — a quarter-megabyte literal
 * is something oxfmt reflows on every run — and the string is built with a second JSON.stringify
 * because the projection carries hundreds of quote characters. The notice is a `/*!` legal comment:
 * esbuild strips ordinary block comments from dist, and MIT's "all copies or substantial portions"
 * is about the published copy.
 */
export function renderHtmlSpecModule(data, { version, license, generatorCommand }) {
  const notice = license
    .split('\n')
    .map((l) => ` * ${l}`.trimEnd())
    .join('\n');
  const body = JSON.stringify(JSON.stringify(data));
  return `/*!
 * HTML spec data projected from @markuplint/html-spec@${version} — https://github.com/markuplint/markuplint
 *
${notice}
 */
// Generated by \`${generatorCommand}\`. Do not edit; test/html-spec.test.ts fails on drift.
import type { HtmlSpecData } from './types.js';

export const HTML_SPEC_VERSION = '${version}';
export const HTML_SPEC: HtmlSpecData = JSON.parse(${body});
`;
}
