// Pure functions for generating schema-vocabulary.generated.ts from schema-dts's type declarations.
// Split from gen-schema-vocab.mjs (the thin I/O main) so test/schema-vocabulary.test.mjs can import
// the extraction logic directly and re-run it against the installed schema-dts, mirroring
// resolve-action-pin.mjs / gen-action-pin.mjs in packages/cli/scripts.
import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import ts from 'typescript';

const require = createRequire(import.meta.url);

/**
 * Every schema.org type is an exported `type` alias in schema-dts's .d.ts; interfaces (`*Base`,
 * `*Leaf`) are excluded by node kind already. These names are the exceptions that slip through as
 * type aliases anyway: the four generic helpers from the design spike (`WithContext`, `Graph`,
 * `SchemaValue`, `IdReference` — the latter two aren't actually exported type aliases in 2.0.0
 * (module-private and a re-export respectively), kept here so a future schema-dts release that
 * changes their shape doesn't silently reintroduce them), plus stragglers found by inspecting the
 * 2.0.0 output: `WithActionConstraints` (action input/output constraint helper) and the `*Leaf`
 * variants of the Role family (`EmployeeRole`/`LinkRole`/`OrganizationRole`/`PerformanceRole`/`Role`
 * are real schema.org types with generic parameters, but their `*Leaf` companions are TS-internal
 * and never a valid `@type` value).
 */
const EXCLUDED_ALIASES = new Set([
  'WithContext',
  'Graph',
  'SchemaValue',
  'IdReference',
  'WithActionConstraints',
  'EmployeeRoleLeaf',
  'LinkRoleLeaf',
  'OrganizationRoleLeaf',
  'PerformanceRoleLeaf',
  'RoleLeaf'
]);

/** Locate schema-dts's type declarations via its `package.json` `types` field, plus its version. */
export function resolveSchemaDts() {
  const pkgPath = require.resolve('schema-dts/package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  return { dtsPath: join(dirname(pkgPath), pkg.types), version: pkg.version };
}

/**
 * Exported type alias names from schema-dts's .d.ts, normalized to schema.org's actual `@type`
 * strings. One normalization is needed: TS identifiers can't start with a digit, so schema-dts
 * prefixes those names with `_` (`_3DModel`) — the JSON-LD `@type` value has no such restriction
 * and is the digit-leading form (`"3DModel"`), so that prefix is stripped. Every other exported
 * alias name already equals its `@type` string, including the ~80 external-vocabulary names
 * (`unece_org_vocab_...`) whose *actual* `@type` value is a full IRI: harmless to leave as-is here
 * since the vocabulary check that consumes this catalog skips any `@type` value containing `:` or
 * `/` before ever doing a lookup, so those bare identifiers are never matched against real markup.
 */
export function extractSchemaOrgTypes(dtsPath) {
  const src = readFileSync(dtsPath, 'utf8');
  const sourceFile = ts.createSourceFile(dtsPath, src, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const names = [];
  sourceFile.forEachChild((node) => {
    if (!ts.isTypeAliasDeclaration(node)) return;
    const isExported = ts.getModifiers(node)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword) ?? false;
    if (!isExported) return;
    const name = node.name.text;
    if (EXCLUDED_ALIASES.has(name)) return;
    names.push(name.replace(/^_(?=\d)/, ''));
  });
  return names;
}

const MIN_COUNT = 700;
const MAX_COUNT = 1500;

/**
 * Render the committed module. Throws (writing nothing) if the count falls outside the sanity band —
 * an upstream schema-dts shape change should fail the generator loudly, not commit a gutted catalog.
 */
export function renderSchemaVocabModule(names, { generatorCommand, schemaDtsVersion }) {
  const sorted = [...new Set(names)].sort();
  if (sorted.length < MIN_COUNT || sorted.length > MAX_COUNT) {
    throw new Error(
      `schema-dts@${schemaDtsVersion} yielded ${sorted.length} type names, outside the expected ${MIN_COUNT}-${MAX_COUNT} band. ` +
        `Sample: ${sorted.slice(0, 10).join(', ')}`
    );
  }
  // The space-joined single-string encoding below can't represent these characters.
  const unencodable = sorted.filter((n) => /[\s'\\`]/.test(n));
  if (unencodable.length > 0) {
    throw new Error(`type names contain characters the space-joined encoding can't hold: ${unencodable.join(', ')}`);
  }
  return `// Generated by \`${generatorCommand}\` from schema-dts@${schemaDtsVersion} — do not edit by hand.
// Regenerate after bumping schema-dts; test/schema-vocabulary.test.mjs fails the build on drift.

/** Every schema.org type name schema-dts exports, for validating JSON-LD \`@type\` values. */
export const SCHEMA_ORG_TYPES: ReadonlySet<string> = new Set('${sorted.join(' ')}'.split(' '));
`;
}
