export const WORKFLOW_PATH = '.github/workflows/svelte-vitals.yml';

export interface WorkflowPlan {
  status: 'created' | 'exists' | 'updated';
  content?: string;
}

/**
 * Decide what to do with the generated workflow file, mirroring the `install` wizard's
 * WriteStatus convention: no existing file → 'created'; an existing file with no
 * --force → 'exists' (left untouched, idempotent re-runs); --force → 'updated'.
 * Content generation is the caller's job (`ci/cli.ts`) — this function only decides.
 */
export function planWorkflowWrite(existing: string | undefined, force: boolean): WorkflowPlan {
  if (existing === undefined) return { status: 'created' };
  if (!force) return { status: 'exists' };
  return { status: 'updated' };
}

/**
 * Build the GitHub Actions workflow that gates PRs on svelte-vitals findings.
 *
 * Design (see plans/015-ci-install-command.md for the full rationale):
 * - Runs the scan twice: once for inline annotations (`--reporter github`) and once for
 *   the Markdown summary (`--reporter md`). Static analysis is seconds long, so the
 *   duplication buys simplicity over threading one reporter's output into both sinks.
 * - `--diff origin/<base>` scopes to files the PR actually touches; `--baseline origin/<base>`
 *   (Plan 014) further narrows to findings that are newly introduced, not pre-existing ones
 *   in touched files. `fetch-depth: 0` is required for both to resolve the base ref.
 * - The PR comment is sticky: a `<!-- svelte-vitals-report -->` marker lets a subsequent
 *   run update the same comment instead of piling up new ones.
 * - `continue-on-error: true` on the `scan` step lets the workflow keep running (to post the
 *   summary comment) even when svelte-vitals exits 1; the final `Gate` step re-raises the
 *   failure by checking `steps.scan.outcome` so the job still fails in that case.
 */
export function buildWorkflowYaml(opts: { version: string }): string {
  const v = opts.version;
  return [
    `# Generated by \`svelte-vitals ci install\` (svelte-vitals ${v}).`,
    '# Re-run with --force to regenerate.',
    'name: svelte-vitals',
    '',
    'on:',
    '  pull_request:',
    '',
    'permissions:',
    '  contents: read',
    '  pull-requests: write',
    '',
    'jobs:',
    '  svelte-vitals:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '        with:',
    '          fetch-depth: 0',
    '      - uses: actions/setup-node@v4',
    '        with:',
    '          node-version: 24',
    '      - name: Scan (inline annotations + gate)',
    '        id: scan',
    '        continue-on-error: true',
    '        run: >',
    `          npx -y svelte-vitals@${v} .`,
    '          --diff origin/${{ github.base_ref }}',
    '          --baseline origin/${{ github.base_ref }}',
    '          --reporter github',
    '      - name: Markdown summary',
    '        run: >',
    `          npx -y svelte-vitals@${v} .`,
    '          --diff origin/${{ github.base_ref }}',
    '          --baseline origin/${{ github.base_ref }}',
    '          --reporter md > svelte-vitals-report.md || true',
    '      - name: Job summary',
    '        run: cat svelte-vitals-report.md >> "$GITHUB_STEP_SUMMARY"',
    '      - name: PR comment (sticky)',
    '        uses: actions/github-script@v7',
    '        with:',
    '          script: |',
    "            const fs = require('fs');",
    "            const marker = '<!-- svelte-vitals-report -->';",
    "            const body = marker + '\\n' + fs.readFileSync('svelte-vitals-report.md', 'utf8');",
    '            const { data: comments } = await github.rest.issues.listComments({',
    '              ...context.repo, issue_number: context.issue.number, per_page: 100',
    '            });',
    '            const mine = comments.find(c => c.body && c.body.startsWith(marker));',
    '            if (mine) {',
    '              await github.rest.issues.updateComment({ ...context.repo, comment_id: mine.id, body });',
    '            } else {',
    '              await github.rest.issues.createComment({ ...context.repo, issue_number: context.issue.number, body });',
    '            }',
    '      - name: Gate',
    "        if: steps.scan.outcome == 'failure'",
    '        run: |',
    '          echo "svelte-vitals found blocking issues (see annotations above)."',
    '          exit 1',
    ''
  ].join('\n');
}
