export const WORKFLOW_PATH = '.github/workflows/svelte-vitals.yml';

// Kept in lockstep with the pin this repo's own workflows use (.github/workflows/ci.yml,
// release.yml, deploy-docs.yml) — bump both together when actions/checkout cuts a new release.
// test/ci/lockstep.test.ts asserts this against .github/workflows/ci.yml directly.
export const CHECKOUT_SHA = '3d3c42e5aac5ba805825da76410c181273ba90b1';
export const CHECKOUT_VERSION = 'v7.0.1';

interface WorkflowPlan {
  status: 'created' | 'exists' | 'updated';
  content?: string;
}

/**
 * Decide what to do with the generated workflow file, mirroring the `install` wizard's
 * WriteStatus convention: no existing file → 'created'; an existing file with no
 * --force → 'exists' (left untouched, idempotent re-runs); --force → 'updated'.
 * Content generation is the caller's job (`gunshi/ci.ts`) — this function only decides.
 */
export function planWorkflowWrite(existing: string | undefined, force: boolean): WorkflowPlan {
  if (existing === undefined) return { status: 'created' };
  if (!force) return { status: 'exists' };
  return { status: 'updated' };
}

/**
 * Build the short GitHub Actions workflow that calls the `svelte-vitals-action` GitHub
 * Action (issue #154 — replaces the old ~60-line inline template; see
 * plans/020-reusable-github-action.md). The action itself owns annotations, the job
 * summary, the sticky PR comment, and the gate — `ci install` only scaffolds the call,
 * pinned to a commit SHA with a same-line version comment. `actions/checkout` is pinned
 * the same way, matching this repo's own `actions/checkout@<sha> # vX.Y.Z` convention
 * (.github/workflows/ci.yml etc.) rather than a floating tag. `svelte-vitals-action` lives
 * in its own dedicated repository (not a subdirectory of this monorepo), so its tags are
 * plain `vX.Y.Z` — Renovate's github-actions manager parses that natively, no special
 * comment format needed.
 */
export function buildWorkflowYaml(opts: { actionSha: string; actionVersion: string }): string {
  const { actionSha, actionVersion } = opts;
  return [
    '# Generated by svelte-vitals (`ci install` or `install --client ci-workflow`).',
    '# Re-run with --force to regenerate.',
    'name: svelte-vitals',
    '',
    'on:',
    '  pull_request:',
    '',
    'permissions:',
    '  contents: read',
    '  pull-requests: write',
    '',
    'jobs:',
    '  svelte-vitals:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    `      - uses: actions/checkout@${CHECKOUT_SHA} # ${CHECKOUT_VERSION}`,
    '        with:',
    '          fetch-depth: 0',
    '          persist-credentials: false',
    `      - uses: oekazuma/svelte-vitals-action@${actionSha} # v${actionVersion}`,
    '        with:',
    '          diff: origin/${{ github.base_ref }}',
    '          baseline: origin/${{ github.base_ref }}',
    ''
  ].join('\n');
}
