// Shared by scripts/gen-docs.mjs (writes the module) and test/docs-embed.test.mjs (fails the
// build when the committed module drifts from packages/cli/docs/). Same generator/staleness
// pairing as scripts/rules-index.mjs.
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptsDir = dirname(fileURLToPath(import.meta.url));

/** Markdown sources, one file per `docs show <name>` topic. */
export const DOCS_DIR = join(scriptsDir, '..', 'docs');
/** The committed module the CLI imports. */
export const GENERATED_PATH = join(scriptsDir, '..', 'src', 'docs', 'generated.ts');

/**
 * Split `---\ntitle: …\ndescription: …\n---` off the front of a topic file.
 *
 * The frontmatter is deliberately minimal: a `title` for the rendered heading and a
 * `description` that `docs list` shows, so a reader picks a topic without paying to read all of
 * them. Anything else is a parse error rather than being silently dropped — a topic with no
 * description is invisible in the listing, which is the one failure that would go unnoticed.
 */
export function parseTopic(fileName, raw) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(raw);
  if (!match) throw new Error(`${fileName}: missing --- frontmatter block`);
  const [, front, body] = match;
  const read = (key) => {
    const hit = new RegExp(`^${key}:\\s*(.+)$`, 'm').exec(front);
    if (!hit) throw new Error(`${fileName}: frontmatter has no \`${key}\``);
    return hit[1].trim();
  };
  return {
    name: fileName.replace(/\.md$/, ''),
    title: read('title'),
    description: read('description'),
    body: body.trim()
  };
}

/** Every topic, ordered by filename so the listing and the module are deterministic. */
export function readTopics(dir = DOCS_DIR) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => parseTopic(f, readFileSync(join(dir, f), 'utf8')));
}

/** Render the committed TypeScript module. */
export function renderModule(topics) {
  const entries = topics
    .map(
      (t) =>
        `  {\n    name: ${JSON.stringify(t.name)},\n    title: ${JSON.stringify(t.title)},\n` +
        `    description: ${JSON.stringify(t.description)},\n    body: ${JSON.stringify(t.body)}\n  }`
    )
    .join(',\n');
  return `// Generated by \`pnpm --filter svelte-vitals run gen:docs\` from packages/cli/docs/*.md.
// Do not edit by hand — edit the markdown and regenerate. test/docs-embed.test.mjs fails the
// build if this file drifts.
//
// The topics are embedded rather than fetched so that what a reader gets always matches the
// version of the CLI they are running, and works with no network.

/** One \`svelte-vitals docs show <name>\` topic. */
export interface EmbeddedDoc {
  /** Filename stem — the \`<name>\` argument. */
  name: string;
  title: string;
  /** One line, shown by \`docs list\` so a topic can be chosen without reading it. */
  description: string;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

export const EMBEDDED_DOCS: EmbeddedDoc[] = [
${entries}
];
`;
}
