// Shared by scripts/gen-docs.mjs (writes the module) and test/docs-embed.test.mjs (fails the
// build when the committed module drifts from packages/cli/docs/). Same generator/staleness
// pairing as scripts/rules-index.mjs.
import { readdirSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptsDir = dirname(fileURLToPath(import.meta.url));

/** Markdown sources, one file per `docs show <name>` topic. */
export const DOCS_DIR = join(scriptsDir, '..', 'docs');
/** The committed module the CLI imports. */
export const GENERATED_PATH = join(scriptsDir, '..', 'src', 'docs', 'generated.ts');

/** Every key a topic's frontmatter may carry, and must carry. */
export const FRONTMATTER_KEYS = ['title', 'description'];

/**
 * Split `---\ntitle: …\ndescription: …\n---` off the front of a topic file.
 *
 * The frontmatter is deliberately minimal: a `title` for the rendered heading and a
 * `description` that `docs list` shows, so a reader picks a topic without paying to read all of
 * them. Anything else is a parse error rather than being silently dropped — a topic with no
 * description is invisible in the listing, which is the one failure that would go unnoticed.
 */
export function parseTopic(fileName, raw) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(raw);
  if (!match) throw new Error(`${fileName}: missing --- frontmatter block`);
  const [, front, body] = match;

  // Parse the whole block rather than grepping for the two keys we want, so a typo'd or
  // duplicated key fails the build instead of silently producing a topic with no description.
  const seen = new Map();
  for (const line of front.split(/\r?\n/)) {
    if (line.trim() === '') continue;
    const kv = /^([A-Za-z][\w-]*):\s*(.*)$/.exec(line);
    if (!kv) throw new Error(`${fileName}: frontmatter line is not \`key: value\`: ${line}`);
    const [, key, value] = kv;
    if (!FRONTMATTER_KEYS.includes(key)) {
      throw new Error(`${fileName}: unknown frontmatter key \`${key}\`; expected ${FRONTMATTER_KEYS.join(', ')}`);
    }
    if (seen.has(key)) throw new Error(`${fileName}: duplicate frontmatter key \`${key}\``);
    if (value.trim() === '') throw new Error(`${fileName}: frontmatter \`${key}\` is empty`);
    seen.set(key, value.trim());
  }
  for (const key of FRONTMATTER_KEYS) {
    if (!seen.has(key)) throw new Error(`${fileName}: frontmatter has no \`${key}\``);
  }

  return {
    name: fileName.replace(/\.md$/, ''),
    title: seen.get('title'),
    description: seen.get('description'),
    body: body.trim()
  };
}

/** Every topic, ordered by filename so the listing and the module are deterministic. */
export function readTopics(dir = DOCS_DIR) {
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .map((f) => parseTopic(f, readFileSync(join(dir, f), 'utf8')));
}

/** Render the committed TypeScript module. */
export function renderModule(topics) {
  const entries = topics
    .map(
      (t) =>
        `  {\n    name: ${JSON.stringify(t.name)},\n    title: ${JSON.stringify(t.title)},\n` +
        `    description: ${JSON.stringify(t.description)},\n    body: ${JSON.stringify(t.body)}\n  }`
    )
    .join(',\n');
  return `// Generated by \`pnpm --filter svelte-vitals run gen:docs\` from packages/cli/docs/*.md.
// Do not edit by hand — edit the markdown and regenerate. test/docs-embed.test.mjs fails the
// build if this file drifts.
//
// The topics are embedded rather than fetched so that what a reader gets always matches the
// version of the CLI they are running, and works with no network.

/** One \`svelte-vitals docs show <name>\` topic. */
export interface EmbeddedDoc {
  /** Filename stem — the \`<name>\` argument. */
  name: string;
  title: string;
  /** One line, shown by \`docs list\` so a topic can be chosen without reading it. */
  description: string;
  /** Markdown body, frontmatter stripped. */
  body: string;
}

export const EMBEDDED_DOCS: EmbeddedDoc[] = [
${entries}
];
`;
}
